version: '3.8'

services:

  django:
    container_name: django
    build:
      context: ./django_celery
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./django_celery:/usr/src/app/
    ports:
      - 8001:8000
    environment:
      - DEBUG=1
      - SECRET_KEY=1Q1Q1Q1Q1Q1Q1Q1Q1Q1Q
      - ALLOWED_HOSTS=localhost,127.0.0.1
